### ISSUE TITLE
Adding more than 100 entries in 'Get Questionnaires"

### ISSUE THREAD

**Issue by SamHarsha** [arthur-shaw/susoapi#46] opened 2024-04-04 06:54 UTC
Hello,
I was trying to get a list of questionnaires on our workspace (there are around 200) and the dataframe returns 100 values. I was trying to follow up on the discussion linked in one of the open issues and I get a sense that it is done to not overwhelm the servers. But can you suggest how can I get the complete list of questionnaires? 
I specifically want questionnaires matching a particular word "baseline" in the title and I thought I could filter after I get the entire dataframe. But if there is a way I can incorporate that in the main GET request, that also works.

**Comment by arthur-shaw** [comment] 2024-04-04 17:41
Duplicate of #8

**Closed by arthur-shaw** 2024-04-04 17:41 UTC
